// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "softtek-techtrial",
    "version": "1"
  },
  "paths": {
    "/newJedi": {
      "post": {
        "summary": "createJedi",
        "description": "",
        "operationId": "createJedi.post./newJedi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getJedis": {
      "get": {
        "summary": "getJedis",
        "description": "",
        "operationId": "getJedis.get./getJedis",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getResources": {
      "get": {
        "summary": "getResources",
        "description": "",
        "operationId": "getResources.get./getResources",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getFilms": {
      "get": {
        "summary": "getFilms",
        "description": "",
        "operationId": "getFilms.get./getFilms",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getTranslate": {
      "get": {
        "summary": "getTranslate",
        "description": "",
        "operationId": "getTranslate.get./getTranslate",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};